AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Include:
    - 'lib/**/*'
    - 'spec/**/*_spec.rb'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspace'
  DisplayCopNames: true

require:
  - rubocop-rspec
  - rubocop-rake

### Layouts ------------------------------------------------------------

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

### Metrics ------------------------------------------------------------

Metrics:
  Enabled: false

### Naming -------------------------------------------------------------

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

### Styles -------------------------------------------------------------

Style/CombinableLoops:
  Enabled: false # there is case that it can't combined loop.

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false # it is easier to read `size > 0` than `size.positive?`

Style/OptionalBooleanParameter:
  Enabled: false # it is necessary to change distructively.

Style/ParallelAssignment:
  Enabled: false # one line style is compact.

Style/PreferredHashMethods:
  Enabled: false

Style/SymbolArray:
  Enabled: false # general array literal is easy to read. no problem.

Style/ZeroLengthPredicate:
  Enabled: false # it is so easy to read `a.size > 0` as `!a.empty?`

### RSpec --------------------------------------------------------------

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

RSpec/FilePath:
  Enabled: false # too many offense

RSpec/ImplicitSubject:
  Enabled: false # too many offenses

RSpec/MultipleExpectations:
  Max: 15

RSpec/NestedGroups:
  Max: 5

RSpec/PredicateMatcher:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false # too many offenses
