AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Include:
    - 'lib/**/*'
  Exclude:
    - 'vendor/**/*'
    - 'benchmarks/*'
    - 'profile/*'
  DisplayCopNames: true
  SuggestExtensions: false

### Layouts ------------------------------------------------------------

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/LineLength:
  Max: 120

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

### Metrics ------------------------------------------------------------

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

### Naming -------------------------------------------------------------

Naming/VariableNumber:
  EnforcedStyle: snake_case

### Styles -------------------------------------------------------------

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  EnforcedStyle: compact

Style/FormatString:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: true

### RSpec --------------------------------------------------------------

require:
  - rubocop-rspec

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 5
