AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Include:
    - 'lib/**/*'
    - 'Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'benchmarks/*'
    - 'profile/*'
  DisplayCopNames: true

require:
  - rubocop-rspec
  - rubocop-rake

### Layouts ------------------------------------------------------------

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  Exclude:
      - spec/**/*

Layout/LineLength:
  Max: 120

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceAroundOperators:
  Exclude:
    - spec/**/*

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

### Metrics ------------------------------------------------------------

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 225

Metrics/ParameterLists:
  Enabled: false
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

### Naming -------------------------------------------------------------

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

### Styles -------------------------------------------------------------

Style/AndOr:
  EnforcedStyle: conditionals

Style/CombinableLoops:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  EnforcedStyle: compact

Style/FormatString:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: true

### RSpec --------------------------------------------------------------

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5
