language:
  ruby

rvm:
  - '2.5.0'
  - '2.6.0'
  - '2.7.0'

script:
  - bundle exec rspec
  - bundle exec rubocop

install:
  - gem install bundler
  - gem install rainbow -v '2.2.1'
  - sudo apt-get update -qq
  - bundle install
